"""Add country field to score

Revision ID: 2de08f9a1cf5
Revises: 9689ad3bb8fc
Create Date: 2024-06-05 23:09:27.475203

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2de08f9a1cf5'
down_revision = '9689ad3bb8fc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('score', schema=None) as batch_op:
        batch_op.add_column(sa.Column('country', sa.String(length=150), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('score', schema=None) as batch_op:
        batch_op.drop_column('country')

    # ### end Alembic commands ###
