"""empty message

Revision ID: 949841325e7a
Revises: 2de08f9a1cf5
Create Date: 2024-06-07 23:12:42.305428

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '949841325e7a'
down_revision = '2de08f9a1cf5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('display_country', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('display_country')

    # ### end Alembic commands ###
